version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://brunasanthiago:admin123@cluster0.52wswb1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: brunasanthiago
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: