version: '3'

services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"  
    volumes:
      - .:/app 
    env_file:
      - .env
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
